// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLFOITwzznb0bInzjdD1flbNGTAwGZZvc',
    appId: '1:191954006345:web:9804abe94c0e949cfbaa98',
    messagingSenderId: '191954006345',
    projectId: 'flutter-chat-app-5ea11',
    authDomain: 'flutter-chat-app-5ea11.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5ea11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW-2A2NHkLQ90EsMfKO9EGvfK1ftliid4',
    appId: '1:191954006345:android:14378ab653cb4e2afbaa98',
    messagingSenderId: '191954006345',
    projectId: 'flutter-chat-app-5ea11',
    storageBucket: 'flutter-chat-app-5ea11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_e2cag1g9-1RczvabFYNwUXHtjxjHnKk',
    appId: '1:191954006345:ios:359e70f9f66fdc8ffbaa98',
    messagingSenderId: '191954006345',
    projectId: 'flutter-chat-app-5ea11',
    storageBucket: 'flutter-chat-app-5ea11.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}